# [START gae_quickstart_yaml]

runtime: python27
threadsafe: yes

handlers:

- url: /
  static_files: default/index.html
  upload: default/index.html

- url: /view1
  static_files: default/index.html
  upload: default/index.html

- url: /publications
  static_files: default/index.html
  upload: default/index.html

- url: /projects
  static_files: default/index.html
  upload: default/index.html

- url: /contact
  static_files: default/index.html
  upload: default/index.html

- url: /default/(.*\.js\.map)
  static_files: default/\1
  upload: default/(.*\.js\.map)
  http_headers:
    Content-Type: application/octet-stream

- url: /(.+)
  static_files: default/\1
  upload: default/(.*)

# [END gae_quickstart_yaml]